import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-api-key, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: CORS });

  try {
    // Verify caller is authenticated teacher/admin
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return new Response(JSON.stringify({ error: 'Unauthorised' }), { status: 401, headers: CORS });

    const sb = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user } } = await sb.auth.getUser();
    if (!user) return new Response(JSON.stringify({ error: 'Unauthorised' }), { status: 401, headers: CORS });

    const { data: profile } = await sb.from('users').select('role').eq('id', user.id).single();
    if (!profile || !['teacher','admin'].includes(profile.role)) {
      return new Response(JSON.stringify({ error: 'Only teachers and admins can generate worksheets' }), { status: 403, headers: CORS });
    }

    // Get prompt from request body
    const { prompt, preview } = await req.json();
    if (!prompt) return new Response(JSON.stringify({ error: 'No prompt provided' }), { status: 400, headers: CORS });

    const ANTHROPIC_KEY = Deno.env.get('ANTHROPIC_API_KEY') ?? '';
    if (!ANTHROPIC_KEY) return new Response(JSON.stringify({ error: 'AI not configured' }), { status: 500, headers: CORS });

    // Call Anthropic API
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001', // cheapest model — perfect for worksheets
        max_tokens: preview ? 600 : 2000,
        system: `You are an expert Abacus maths teacher at iMathAcademy India generating student worksheets.

CRITICAL OUTPUT RULES — follow exactly:
1. When asked for a JSON array of questions, return ONLY a valid JSON array. No markdown. No bold. No asterisks. No explanation before or after the JSON.
2. Each JSON object must have exactly these fields: "question", "answer", "emoji", "type".
3. The "question" field must contain ONLY the question text — never include the answer inside the question.
4. The "answer" field must contain ONLY the numeric answer — e.g. "36" not "36 (3×12)".
5. Do NOT use ** bold **, _italic_, or any markdown formatting inside JSON strings.
6. Do NOT include the answer inside the question text in any format.
7. All maths must be 100% correct. Verify every answer before writing it.
8. Use Indian names: Aryan, Priya, Ravi, Meera, Rohan, Ananya.`,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok) {
      const err = await response.json();
      console.error('Anthropic error:', err);
      return new Response(JSON.stringify({ error: err.error?.message || 'AI generation failed' }), {
        status: response.status, headers: CORS
      });
    }

    const data = await response.json();
    const text = data.content?.[0]?.text || '';

    // Log usage for monitoring
    console.log(`Worksheet generated by ${user.id} — ${data.usage?.input_tokens} in / ${data.usage?.output_tokens} out tokens`);

    return new Response(JSON.stringify({ text, usage: data.usage }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...CORS }
    });

  } catch (err) {
    console.error('generate-worksheet error:', err);
    return new Response(JSON.stringify({ error: String(err) }), { status: 500, headers: CORS });
  }
});
