import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-api-key, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: CORS });

  try {
    // Verify caller is authenticated teacher/admin
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return new Response(JSON.stringify({ error: 'Unauthorised' }), { status: 401, headers: CORS });

    const sb = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user } } = await sb.auth.getUser();
    if (!user) return new Response(JSON.stringify({ error: 'Unauthorised' }), { status: 401, headers: CORS });

    const { data: profile } = await sb.from('users').select('role').eq('id', user.id).single();
    if (!profile || !['teacher','admin'].includes(profile.role)) {
      return new Response(JSON.stringify({ error: 'Only teachers and admins can generate worksheets' }), { status: 403, headers: CORS });
    }

    // Get prompt from request body
    const { prompt, preview } = await req.json();
    if (!prompt) return new Response(JSON.stringify({ error: 'No prompt provided' }), { status: 400, headers: CORS });

    const ANTHROPIC_KEY = Deno.env.get('ANTHROPIC_API_KEY') ?? '';
    if (!ANTHROPIC_KEY) return new Response(JSON.stringify({ error: 'AI not configured' }), { status: 500, headers: CORS });

    // Call Anthropic API
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001', // cheapest model — perfect for worksheets
        max_tokens: preview ? 600 : 2000,
        system: `You are an expert Abacus maths teacher at iMathAcademy India. 
Generate age-appropriate, curriculum-aligned worksheets. 
Always respond in the exact format requested with clear section headers using ## markers.
For Indian context always use Indian names (Aryan, Priya, Ravi, Meera, Rohan, Ananya).
All maths must be 100% accurate — double-check every answer.`,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok) {
      const err = await response.json();
      console.error('Anthropic error:', err);
      return new Response(JSON.stringify({ error: err.error?.message || 'AI generation failed' }), {
        status: response.status, headers: CORS
      });
    }

    const data = await response.json();
    const text = data.content?.[0]?.text || '';

    // Log usage for monitoring
    console.log(`Worksheet generated by ${user.id} — ${data.usage?.input_tokens} in / ${data.usage?.output_tokens} out tokens`);

    return new Response(JSON.stringify({ text, usage: data.usage }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...CORS }
    });

  } catch (err) {
    console.error('generate-worksheet error:', err);
    return new Response(JSON.stringify({ error: String(err) }), { status: 500, headers: CORS });
  }
});
