import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-api-key, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: CORS });

  try {
    // Verify caller is authenticated teacher/admin
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return new Response(JSON.stringify({ error: 'Unauthorised' }), { status: 401, headers: CORS });

    const sb = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user } } = await sb.auth.getUser();
    if (!user) return new Response(JSON.stringify({ error: 'Unauthorised' }), { status: 401, headers: CORS });

    const { data: profile } = await sb.from('users').select('role').eq('id', user.id).single();
    if (!profile || !['teacher','admin'].includes(profile.role)) {
      return new Response(JSON.stringify({ error: 'Only teachers and admins can generate worksheets' }), { status: 403, headers: CORS });
    }

    // Get prompt from request body
    const { prompt, preview } = await req.json();
    if (!prompt) return new Response(JSON.stringify({ error: 'No prompt provided' }), { status: 400, headers: CORS });

    const ANTHROPIC_KEY = Deno.env.get('ANTHROPIC_API_KEY') ?? '';
    if (!ANTHROPIC_KEY) return new Response(JSON.stringify({ error: 'AI not configured' }), { status: 500, headers: CORS });

    // Call Anthropic API
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001', // cheapest model — perfect for worksheets
        max_tokens: preview ? 600 : 2000,
        system: `You are an expert Abacus maths teacher at iMathAcademy India generating student worksheets.

CRITICAL OUTPUT RULES:
1. Return ONLY a valid JSON array. No markdown fences, no explanations, nothing outside the JSON.
2. Each object: {"question": "...", "answer": "...", "emoji": "...", "type": "..."}
3. THE QUESTION MUST NEVER CONTAIN THE ANSWER. 
   - WRONG: "Priya has 4 bowls × 6 pieces = 24 pieces of fruit"
   - WRONG: "4 × 6 = 24"
   - CORRECT: "Priya has 4 bowls with 6 pieces of fruit each. How many pieces in total?"
   - CORRECT: "4 × 6 = ?"
4. Story questions must END with a question — never state the answer in the story.
   - WRONG: "Aryan has 3 × 12 mangoes = 36 mangoes"
   - CORRECT: "Aryan has 3 baskets with 12 mangoes each. How many mangoes does he have?"
5. The "answer" field contains ONLY the number: "36" not "36 mangoes" not "36 (3×12)".
6. No ** bold **, no *italic*, no markdown of any kind inside JSON strings.
7. All maths must be 100% correct. Verify each answer.
8. Use Indian names: Aryan, Priya, Ravi, Meera, Rohan, Ananya.`,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok) {
      const err = await response.json();
      console.error('Anthropic error:', err);
      return new Response(JSON.stringify({ error: err.error?.message || 'AI generation failed' }), {
        status: response.status, headers: CORS
      });
    }

    const data = await response.json();
    const text = data.content?.[0]?.text || '';

    // Log usage for monitoring
    console.log(`Worksheet generated by ${user.id} — ${data.usage?.input_tokens} in / ${data.usage?.output_tokens} out tokens`);

    return new Response(JSON.stringify({ text, usage: data.usage }), {
      status: 200,
      headers: { 'Content-Type': 'application/json', ...CORS }
    });

  } catch (err) {
    console.error('generate-worksheet error:', err);
    return new Response(JSON.stringify({ error: String(err) }), { status: 500, headers: CORS });
  }
});
